component_name = "foo_ui_columns"
solution_path = "vc18\\columns_ui-public.sln"
output_path = "component-packages"
x86_build_path = "vc18\\release-win32-v145"
x64_build_path = "vc18\\release-x64-v145"
