//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by foo_ui_columns.rc
//
#define IDC_TOOLS                       3
#define IDC_ADD                         4
#define IDD_PREFS_MAIN                  101
#define IDD_PREFS_PVIEW_GLOBALS         102
#define IDC_PICK                        102
#define IDD_BUTTONS_OPTIONS             105
#define IDB_BLANK                       117
#define IDD_QUICK_SETUP                 129
#define IDB_LIGHT_NOCOVER               137
#define IDI_LIGHT_PLAY                  147
#define IDI_LIGHT_STOP                  148
#define IDI_LIGHT_NEXT                  149
#define IDI_LIGHT_RAND                  150
#define IDI_LIGHT_OPEN                  151
#define IDI_LIGHT_PAUSE                 152
#define IDI_LIGHT_PREV                  153
#define IDI_LIGHT_STARON                155
#define IDI_LIGHT_STAROFF               156
#define IDI_LIGHT_RESET                 157
#define IDI_DARK_NEXT                   158
#define IDI_DARK_OPEN                   159
#define IDI_DARK_PAUSE                  160
#define IDI_DARK_PLAY                   161
#define IDI_DARK_RAND                   162
#define IDI_DARK_PREV                   163
#define IDI_DARK_STOP                   164
#define IDB_DARK_NOCOVER                165
#define IDI_DARK_STAROFF                166
#define IDI_DARK_STARON                 167
#define IDI_DARK_RESET                  168
#define IDI_DARK_PADLOCK                169
#define IDI_LIGHT_PADLOCK               171
#define IDV_LIGHT_PLAY                  172
#define IDV_LIGHT_STOP                  173
#define IDV_LIGHT_NEXT                  174
#define IDV_LIGHT_RAND                  175
#define IDV_LIGHT_OPEN                  176
#define IDV_LIGHT_PAUSE                 177
#define IDV_LIGHT_PREV                  178
#define IDV_LIGHT_STARON                179
#define IDV_LIGHT_STAROFF               180
#define IDV_LIGHT_RESET                 181
#define IDV_DARK_NEXT                   182
#define IDV_DARK_OPEN                   183
#define IDV_DARK_PAUSE                  184
#define IDV_DARK_PLAY                   185
#define IDV_DARK_RAND                   186
#define IDV_DARK_PREV                   187
#define IDV_DARK_STOP                   188
#define IDV_DARK_STAROFF                189
#define IDV_DARK_STARON                 190
#define IDV_DARK_RESET                  191
#define IDV_DARK_PADLOCK                192
#define IDV_LIGHT_PADLOCK               193
#define IDV_DARK_STOP_AFTER_CURRENT     194
#define IDV_LIGHT_STOP_AFTER_CURRENT    195
#define IDD_PREFS_PVIEW_GENERAL         196
#define IDI_DARK_STOP_AFTER_CURRENT     196
#define IDD_PREFS_PLAYLISTS_DRAGDROP    197
#define IDI_LIGHT_STOP_AFTER_CURRENT    197
#define IDD_PREFS_LAYOUT_PRESETS        198
#define IDD_RENAME_PLAYLIST             200
#define IDD_PREFS_TAB_HOST              201
#define IDD_PREFS_PLAYLIST_TABS         202
#define IDD_PREFS_SYSTEM_TRAY           203
#define IDD_SPECTRUM_ANALYSER_OPTIONS   204
#define IDD_BUTTON_COMMAND_PICKER       206
#define IDD_FCL_IMPORT                  207
#define IDD_RESULTS                     209
#define IDD_FCL_EXPORT                  210
#define IDD_EDIT_GROUP                  213
#define IDD_PREFS_PVIEW_GROUPS          214
#define IDD_PREFS_FILTER_FIELDS         215
#define IDD_PREFS_FONTS                 216
#define IDD_COLUMN_OPTIONS              218
#define IDD_PREFS_COLUMNS               220
#define IDD_PREFS_STATUS_BAR            221
#define IDD_PREFS_COLOURS               222
#define IDD_PREFS_ARTWORK               223
#define IDD_ITEM_PROPS_OPTIONS          224
#define IDD_ITEM_DETAILS_OPTIONS        225
#define IDD_PREFS_FILTER_APPEARANCE     226
#define IDD_PREFS_FILTER_BEHAVIOUR      227
#define IDD_PREFS_PVIEW_ARTWORK         229
#define IDD_PREFS_LAYOUT_MISC           230
#define IDD_COLUMN_DISPLAY_SCRIPT       231
#define IDD_COLUMN_SORTING_SCRIPT       232
#define IDD_COLUMN_STYLE_SCRIPT         233
#define IDD_PREFS_PLAYLIST_SWITCHER     234
#define IDD_PREFS_DARK_MODE             235
#define IDD_PREFS_STATUS_PANE           236
#define IDD_PREFS_TEXT_RENDERING        237
#define IDD_FONT_AXES                   238
#define IDD_ITEM_DETAILS_PICK_FONT      239
#define IDC_INFOSECTIONS                1003
#define IDC_STRING                      1006
#define IDC_COLOUR                      1007
#define IDC_DBLCLK                      1007
#define IDC_NAME                        1008
#define IDC_WIDTH                       1009
#define IDC_APPLY                       1010
#define IDC_PARTS                       1011
#define IDC_HEIGHT                      1011
#define IDC_PLHEIGHT                    1012
#define IDC_EDITFIELD                   1012
#define IDC_MIDDLE                      1012
#define IDC_CUSTOM_SORT                 1013
#define IDC_SWITCH_DELAY                1013
#define IDC_PADDING                     1013
#define IDC_SORT                        1014
#define IDC_SHOW_COLUMN                 1014
#define IDC_GLOBAL                      1015
#define IDC_HEADER                      1015
#define IDC_AUTOSEND                    1015
#define IDC_GLOBALSORT                  1016
#define IDC_SHOWEMPTY                   1016
#define IDC_CUSTOM_COLOUR               1017
#define IDC_DROP_AT_END                 1017
#define IDC_FCL_IMPORT                  1017
#define IDC_FILTERS_SHOW_COLUMN_TITLES  1017
#define IDC_REVERSE_SORT_TRACKS         1017
#define IDC_VALUE                       1018
#define IDC_FILTERS_ALLOW_SORTING       1018
#define IDC_PLAYLIST_FILTER_STRING      1019
#define IDC_SPIN1                       1019
#define IDC_FCL_EXPORT                  1019
#define IDC_GROUP_NEW                   1019
#define IDC_FILTERS_SHOW_SORT_INDICATORS 1019
#define IDC_ALIGNMENT                   1020
#define IDC_GROUP_DELETE                1020
#define IDC_ARTWORKWIDTHSPIN            1020
#define IDC_BALLOON                     1021
#define IDC_PLAYLIST_FILTER_TYPE        1021
#define IDC_INDENTATION_AMOUNT_SPIN     1021
#define IDC_MCLICK                      1022
#define IDC_GROUP_UP                    1022
#define IDC_MCLICK3                     1023
#define IDC_ELLIPSIS                    1023
#define IDC_PLDRAG                      1024
#define IDC_PLAYLIST_TABS_MCLICK        1025
#define IDC_ACTIVATE_TARGET             1026
#define IDC_TOOLTIPS_CLIPPED            1026
#define IDC_REMOVE                      1027
#define IDC_NOHSCROLL                   1027
#define IDC_GROUP_DOWN                  1027
#define IDC_UP                          1028
#define IDC_SHOW_SYSTRAY                1028
#define IDC_DOWN                        1029
#define IDC_MINIMISE_TO_SYSTRAY         1029
#define IDC_USE_CUSTOM_ICON             1030
#define IDC_NEW                         1030
#define IDC_BROWSE_ICON                 1031
#define IDC_FILTER_HELP                 1031
#define IDC_USE_CUSTOM_HOVER_ICON       1032
#define IDC_AUTOSWITCH                  1034
#define IDC_USE_TRANSPARENCY            1035
#define IDC_PLEDGE                      1035
#define IDC_NOWPL                       1036
#define IDC_INLINE_MODE                 1036
#define IDC_RESET                       1038
#define IDC_COMMAND                     1038
#define IDC_VOL                         1039
#define IDC_TAB1                        1039
#define IDC_SORT_ARROWS                 1039
#define IDC_PLISTEDGE                   1040
#define IDC_SHOW_STATUS                 1040
#define IDC_PLAUTOHIDE                  1041
#define IDC_SHOW_LOCK                   1041
#define IDC_SELTIME                     1042
#define IDC_HOVER_ICON_PATH             1042
#define IDC_HHTRACK                     1043
#define IDC_SHOW_STATUSPANE             1043
#define IDC_BROWSE_HOVER_ICON           1043
#define IDC_TFHELP                      1044
#define IDC_SPINPL                      1045
#define IDC_EDIT                        1046
#define IDC_SWITCH_SPIN                 1047
#define IDC_DESC                        1049
#define IDC_SELECTION_MODEL             1049
#define IDC_DROP_USE_STRING             1050
#define IDC_ITEM                        1050
#define IDC_SHOWARTWORK                 1050
#define IDC_DROP_STRING                 1051
#define IDC_SHOW                        1051
#define IDC_TABS_MULTILINE              1052
#define IDC_GROUP                       1052
#define IDC_TEXT_LOCATION               1052
#define IDC_ARTWORKREFLECTION           1052
#define IDC_MENU_DBLCLK                 1053
#define IDC_REMOVE_UNDERSCORES          1053
#define IDC_APPEARANCE                  1053
#define IDC_ICON_SIZE                   1054
#define IDC_TEXT                        1055
#define IDC_USE_CUSTOM_TEXT             1056
#define IDC_PICK_COLOUR                 1057
#define IDC_MENU_DESC                   1058
#define IDC_TREE                        1065
#define IDC_CAPTION                     1066
#define IDC_TOOLBARS                    1067
#define IDC_HIDDEN                      1067
#define IDC_LOCKED                      1068
#define IDC_AUTOHIDE                    1069
#define IDC_TOGGLE_AREA                 1070
#define IDC_USE_CUSTOM_TITLE            1071
#define IDC_RESET_TOOLBARS              1073
#define IDC_USE_CUSTOM_SHOW_DELAY       1077
#define IDC_SHOW_DELAY                  1078
#define IDC_SHOW_DELAY_SPIN             1079
#define IDC_PLAYLIST_DOUBLE             1080
#define IDC_HIDE_DELAY_SPIN             1080
#define IDC_HIDE_DELAY                  1081
#define IDC_USE_PLAYLIST_TF             1081
#define IDC_PLAYLIST_MIDDLE             1081
#define IDC_PLAYLIST_TF                 1082
#define IDC_CUSTOM_DIVIDER_WIDTH        1083
#define IDC_CUSTOM_DIVIDER_WIDTH_SPIN   1084
#define IDC_CUSTOM_FRAME                1088
#define IDC_CAPTIONSTYLE                1092
#define IDC_CONFIGURE                   1093
#define IDC_BARS                        1100
#define IDC_CHANGE_SEL_INACTIVE_BACK    1100
#define IDC_FRAME_COMBO                 1101
#define IDC_SCALE                       1102
#define IDC_CHANGE_FRAME                1103
#define IDC_VERTICAL_SCALE              1103
#define IDC_CHANGE_SEL_FORE             1106
#define IDC_CHANGE_SEL_INACTIVE_FORE    1110
#define IDC_CHANGE_TEXT_FORE            1116
#define IDC_TRANSPARENCY_LEVEL          1122
#define IDC_TRANSPARENCY_SPIN           1123
#define IDC_PRESETS                     1124
#define IDC_NEW_PRESET                  1125
#define IDC_DELETE_PRESET               1126
#define IDC_RENAME_PRESET               1127
#define IDC_RESET_PRESETS               1128
#define IDC_CUSTOM_TITLE                1129
#define IDC_DUPLICATE_PRESET            1130
#define IDC_COLOURS_SCHEME              1131
#define IDC_COLOURS_ELEMENT             1132
#define IDC_THEMING                     1134
#define IDC_DEST                        1135
#define IDC_DARK_MODE                   1135
#define IDC_SORT_STRING                 1143
#define IDC_CHANGE_TEXT_BACK            1149
#define IDC_CHANGE_SELBACK              1150
#define IDC_EDGESTYLE                   1155
#define IDC_PRECEDENCE                  1156
#define IDC_HALIGN                      1156
#define IDC_CLICK_ACTION                1156
#define IDC_VALIGN                      1157
#define IDC_ARTWORKWIDTH                1158
#define IDC_QUICKSETUP                  1159
#define IDC_SPINPADDING                 1160
#define IDC_SCRIPT                      1162
#define IDC_GROUPING                    1163
#define IDC_SHOWCOLUMNS                 1163
#define IDC_ALLOW_LOCKED_PANEL_RESIZING 1163
#define IDC_GEN_COLOUR                  1164
#define IDC_SHOWGROUPS                  1164
#define IDC_INDENT_GROUPS               1164
#define IDC_USE_CUSTOM_INDENTATION      1165
#define IDC_FORMAT_CODE_GENERATOR       1165
#define IDC_COLOUR_CODE                 1166
#define IDC_TITLE1                      1168
#define IDC_TITLE2                      1169
#define IDC_DISPLAY_SCRIPT              1173
#define IDC_SORTING_SCRIPT              1174
#define IDC_STYLE_SCRIPT                1175
#define IDC_OPEN_DISPLAY_PREFERENCES    1176
#define IDC_VIEW_OLD_ARTWORK_SOURCES    1177
#define IDC_VIEW_OLD_ARTWORK_SOURCES_TEXT 1178
#define IDC_PREVIOUS_OPEN_DISPLAY_PREFERENCES 1179
#define IDC_DARK_MODE_DISABLED          1179
#define IDC_DARK_MODE_ENABLED           1180
#define IDC_DARK_MODE_MESSAGE           1181
#define IDC_SELCOUNT                    1183
#define IDC_DARK_MODE_USE_SYSTEM_SETTING 1183
#define IDC_FONT_ELEMENT                1184
#define IDC_FONT_MODE                   1185
#define IDC_FONT_FAMILY                 1186
#define IDC_WIDTH_SPIN                  1187
#define IDC_FONT_FACE                   1187
#define IDC_HEIGHT_SPIN                 1188
#define IDC_ICON_PATH                   1189
#define IDC_BUTTONS_H1                  1190
#define IDC_BUTTON_OPTIONS_H2           1191
#define IDC_INDENTATION_AMOUNT          1191
#define IDC_TOOLBAR_OPTIONS_H1          1192
#define IDC_H2_TITLE                    1192
#define IDC_FONT_SIZE                   1192
#define IDC_FONT_SIZE_SPIN              1193
#define IDC_RENDERING_MODE              1194
#define IDC_COLOUR_EMOJI_FAMILY         1195
#define IDC_FORCE_GREYSCALE_ANTIALIASING 1196
#define IDC_CONFIGURE_AXES              1197
#define IDC_USE_CUSTOM_EMOJI_PROCESSING 1197
#define IDC_AXIS                        1198
#define IDC_MONOCHROME_EMOJI_FAMILY     1198
#define IDC_AXIS_VALUE                  1200
#define IDC_AXIS_VALUE_SPIN             1201
#define IDC_AXIS_RANGE                  1202
#define IDC_SET_FORMAT_SNIPPET          1203
#define IDC_TEXT_RENDERING_NOTES        1204
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1205
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
