#include "pch.h"

// Note that version.h is automatically generated by a pre-build step.
// If it is missing, then the pre-build step did not execute correctly, and
// the build log should contain more information.
#include "version.h"

VALIDATE_COMPONENT_FILENAME("foo_ui_columns.dll");

DECLARE_COMPONENT_VERSION("Columns UI",

    cui::version,

    "Columns UI\n"
    "Alternative user interface\n"
    "\n"
    "© musicmusic and contributors " CUI_COMPILATION_YEAR "\n"
    "Current version at yuo.be\n"
    "\n"
    "Built on " CUI_COMPILATION_DATE "\n"
    "Columns UI SDK version: " UI_EXTENSION_VERSION

);
