$header_template = @'
#pragma once

// This file is automatically generated by scripts\generate-version.ps1

#define COMPILATION_DATE "{0}"

namespace cui {{

constexpr auto version = u8"{1}";

}}
'@

Try {
    $version = git describe --tags --dirty
} Catch {}

If (-NOT $version) {
    $version = 'unknown'
} ElseIf ($version.Substring(0, 1) -eq 'v') {
    $version = $version.Substring(1)
}

$date = (Get-Date).toString('d MMMM yyyy')
$header = ($header_template -f $date, $version)

Write-Host "Version: $version"
Out-File 'version.h' -Encoding 'UTF8' -InputObject $header
